"""add redirect_url_template to offers

Revision ID: 0e1d82b42fc1
Revises: 19a31450fc2d
Create Date: 2026-09-09 15:55:19.077174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.types


# revision identifiers, used by Alembic.
revision: str = '0e1d82b42fc1'
down_revision: Union[str, None] = '19a31450fc2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('redirect_url_template', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'redirect_url_template')
    # ### end Alembic commands ###
