"""add manual entry fields to affiliate_events

Revision ID: 19a31450fc2d
Revises: 489718ceca81
Create Date: 2026-09-09 15:19:41.870070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.types


# revision identifiers, used by Alembic.
revision: str = '19a31450fc2d'
down_revision: Union[str, None] = '489718ceca81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('affiliate_events', sa.Column('source', sa.Enum('postback', 'manual', name='affiliateeventsource', native_enum=False, length=16), server_default='postback', nullable=False))
    op.add_column('affiliate_events', sa.Column('entered_by', app.models.types.GUID(), nullable=True))
    op.add_column('affiliate_events', sa.Column('channel', sa.String(length=128), nullable=True))
    op.add_column('affiliate_events', sa.Column('validation_flags', app.models.types.JSONBType(), nullable=True))
    op.create_index(op.f('ix_affiliate_events_entered_by'), 'affiliate_events', ['entered_by'], unique=False)
    op.create_foreign_key('affiliate_events_entered_by_fkey', 'affiliate_events', 'users', ['entered_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('affiliate_events_entered_by_fkey', 'affiliate_events', type_='foreignkey')
    op.drop_index(op.f('ix_affiliate_events_entered_by'), table_name='affiliate_events')
    op.drop_column('affiliate_events', 'validation_flags')
    op.drop_column('affiliate_events', 'channel')
    op.drop_column('affiliate_events', 'entered_by')
    op.drop_column('affiliate_events', 'source')
    # ### end Alembic commands ###
