"""initial schema

Revision ID: 489718ceca81
Revises: 
Create Date: 2026-09-07 21:42:11.555934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.types


# revision identifiers, used by Alembic.
revision: str = '489718ceca81'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('geo', sa.String(length=8), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=False),
    sa.Column('budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'paused', 'archived', name='campaignstatus', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_geo'), 'campaigns', ['geo'], unique=False)
    op.create_table('offers',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('partner_name', sa.String(length=255), nullable=False),
    sa.Column('geo', sa.String(length=8), nullable=False),
    sa.Column('commission_model', sa.Enum('cpa', 'revshare', 'hybrid', name='commissionmodel', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('active', 'paused', name='offerstatus', native_enum=False, length=32), nullable=False),
    sa.Column('api_docs_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offers_geo'), 'offers', ['geo'], unique=False)
    op.create_table('users',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'tech_lead', 'compliance', 'affiliate_manager', 'sales_manager', 'smm_manager', 'analyst', name='userrole', native_enum=False, length=32), nullable=False),
    sa.Column('geo_coverage', app.models.types.JSONBType(), nullable=False),
    sa.Column('dialects', app.models.types.JSONBType(), nullable=False),
    sa.Column('telegram_id', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('is_2fa_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('actor_id', app.models.types.GUID(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('meta', app.models.types.JSONBType(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_table('leads',
    sa.Column('lead_id', app.models.types.GUID(), nullable=False),
    sa.Column('external_click_id', sa.String(length=128), nullable=True),
    sa.Column('geo', sa.String(length=8), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('dialect', sa.Enum('levantine', 'moroccan_darija', 'gulf_najdi', 'other', name='dialect', native_enum=False, length=32), nullable=True),
    sa.Column('source_channel', sa.Enum('telegram_ads', 'organic', 'existing_base', 'referral', name='sourcechannel', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('new', 'contacted', 'qualified', 'registered', 'kyc_pending', 'kyc_approved', 'ftd', 'active', 'churned', 'unsubscribed', name='leadstatus', native_enum=False, length=32), nullable=False),
    sa.Column('assigned_manager_id', app.models.types.GUID(), nullable=True),
    sa.Column('offer_id', app.models.types.GUID(), nullable=True),
    sa.Column('telegram_user_id', sa.String(length=64), nullable=True),
    sa.Column('consent_status', sa.Enum('granted', 'revoked', 'unknown', name='consentstatus', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('lead_id')
    )
    op.create_index(op.f('ix_leads_assigned_manager_id'), 'leads', ['assigned_manager_id'], unique=False)
    op.create_index(op.f('ix_leads_external_click_id'), 'leads', ['external_click_id'], unique=False)
    op.create_index(op.f('ix_leads_geo'), 'leads', ['geo'], unique=False)
    op.create_index(op.f('ix_leads_offer_id'), 'leads', ['offer_id'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_index(op.f('ix_leads_telegram_user_id'), 'leads', ['telegram_user_id'], unique=False)
    op.create_table('affiliate_events',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('lead_id', app.models.types.GUID(), nullable=True),
    sa.Column('partner', sa.String(length=64), nullable=False),
    sa.Column('external_event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.Enum('registration', 'kyc_approved', 'ftd', 'deposit', 'withdrawal', 'commission', 'chargeback', name='affiliateeventtype', native_enum=False, length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('raw_payload', app.models.types.JSONBType(), nullable=False),
    sa.Column('normalized_payload', app.models.types.JSONBType(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.lead_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliate_events_external_event_id'), 'affiliate_events', ['external_event_id'], unique=True)
    op.create_index(op.f('ix_affiliate_events_lead_id'), 'affiliate_events', ['lead_id'], unique=False)
    op.create_table('communications',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('lead_id', app.models.types.GUID(), nullable=False),
    sa.Column('manager_id', app.models.types.GUID(), nullable=True),
    sa.Column('channel', sa.Enum('telegram', 'whatsapp', 'webchat', name='communicationchannel', native_enum=False, length=32), nullable=False),
    sa.Column('direction', sa.Enum('inbound', 'outbound', name='communicationdirection', native_enum=False, length=16), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('external_message_id', sa.String(length=128), nullable=True),
    sa.Column('is_ai_suggested', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.lead_id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communications_external_message_id'), 'communications', ['external_message_id'], unique=True)
    op.create_index(op.f('ix_communications_lead_id'), 'communications', ['lead_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('lead_id', app.models.types.GUID(), nullable=False),
    sa.Column('manager_id', app.models.types.GUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('open', 'done', 'cancelled', name='taskstatus', native_enum=False, length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.lead_id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_lead_id'), 'tasks', ['lead_id'], unique=False)
    op.create_index(op.f('ix_tasks_manager_id'), 'tasks', ['manager_id'], unique=False)
    op.create_table('tracking_events',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('lead_id', app.models.types.GUID(), nullable=True),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('click_id', sa.String(length=128), nullable=True),
    sa.Column('campaign_id', sa.String(length=128), nullable=True),
    sa.Column('adset_id', sa.String(length=128), nullable=True),
    sa.Column('creative_id', sa.String(length=128), nullable=True),
    sa.Column('landing_id', sa.String(length=128), nullable=True),
    sa.Column('event_type', sa.Enum('click', 'landing_view', 'lead_created', 'conversation_started', 'manager_assigned', 'registration', 'kyc', 'ftd', 'deposit', 'withdrawal', 'affiliate_commission', 'unsubscribe', 'chargeback', name='trackingeventtype', native_enum=False, length=32), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_payload', app.models.types.JSONBType(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.lead_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracking_events_click_id'), 'tracking_events', ['click_id'], unique=False)
    op.create_index(op.f('ix_tracking_events_event_type'), 'tracking_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_tracking_events_lead_id'), 'tracking_events', ['lead_id'], unique=False)
    op.create_index(op.f('ix_tracking_events_session_id'), 'tracking_events', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracking_events_session_id'), table_name='tracking_events')
    op.drop_index(op.f('ix_tracking_events_lead_id'), table_name='tracking_events')
    op.drop_index(op.f('ix_tracking_events_event_type'), table_name='tracking_events')
    op.drop_index(op.f('ix_tracking_events_click_id'), table_name='tracking_events')
    op.drop_table('tracking_events')
    op.drop_index(op.f('ix_tasks_manager_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_lead_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_communications_lead_id'), table_name='communications')
    op.drop_index(op.f('ix_communications_external_message_id'), table_name='communications')
    op.drop_table('communications')
    op.drop_index(op.f('ix_affiliate_events_lead_id'), table_name='affiliate_events')
    op.drop_index(op.f('ix_affiliate_events_external_event_id'), table_name='affiliate_events')
    op.drop_table('affiliate_events')
    op.drop_index(op.f('ix_leads_telegram_user_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_offer_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_geo'), table_name='leads')
    op.drop_index(op.f('ix_leads_external_click_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_assigned_manager_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_offers_geo'), table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_campaigns_geo'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
