// Страны Лиги арабских государств (ISO 3166-1 alpha-2 + название на русском).
export const ARAB_COUNTRIES: { code: string; name: string }[] = [
  { code: "SY", name: "Сирия" },
  { code: "MA", name: "Марокко" },
  { code: "SA", name: "Саудовская Аравия" },
  { code: "EG", name: "Египет" },
  { code: "IQ", name: "Ирак" },
  { code: "JO", name: "Иордания" },
  { code: "LB", name: "Ливан" },
  { code: "LY", name: "Ливия" },
  { code: "TN", name: "Тунис" },
  { code: "DZ", name: "Алжир" },
  { code: "SD", name: "Судан" },
  { code: "YE", name: "Йемен" },
  { code: "OM", name: "Оман" },
  { code: "AE", name: "ОАЭ" },
  { code: "QA", name: "Катар" },
  { code: "KW", name: "Кувейт" },
  { code: "BH", name: "Бахрейн" },
  { code: "PS", name: "Палестина" },
  { code: "MR", name: "Мавритания" },
  { code: "SO", name: "Сомали" },
  { code: "DJ", name: "Джибути" },
  { code: "KM", name: "Коморы" },
];
